Simple Neural Network


In [0]:
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
"""Sigmoid"""
def activation(x):
  return 1/(1+torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(7) # set the random seeds so things are predictable

# features are 5 random normal variables
features = torch.randn((1,5))
#True weights for our data, random normal variables again
weights = torch.randn_like(features)
#and a true bias term
bias = torch.randn((1,1))

In [0]:
features, weights, bias

(tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]]),
 tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]]),
 tensor([[0.3177]]))

In [0]:
## Calculate the output of this network using the weights and bias tensors

output = activation(torch.sum(features * weights) + bias)


In [0]:
output

tensor([[0.1595]])

In [0]:
## ANother way of doing it 
## weights1 = weights.t() 

weights1 = weights.view(5, 1)
output1 = activation(torch.mm(features, weights1) + bias)
output1

tensor([[0.1595]])

======================Neural network with 2 layers==================

In [0]:
##Generate some data
torch.manual_seed(7)

#features are 3 random normal variables
features = torch.randn((1,3))

#define size of each layer in neural network
n_input = features.shape[1]   #number of input units
n_hidden = 2                  #number of hidden units
n_output = 1                  #number of output units

#weights for inputs to hidden layer
w1 = torch.randn((n_input, n_hidden))

#weights for hidden to output layer
w2 = torch.randn((n_hidden, n_output))

#bias terms for hidden and output layers
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

In [0]:
##Calculating output for this network
h = activation(torch.mm(features, w1)+b1)
output = activation(torch.mm(h, w2)+b2)
output

tensor([[0.3171]])

**Numpy to torch and back**

In [0]:
import numpy as np

In [0]:
a = np.random.rand(4,3)
a

array([[0.22563518, 0.45516341, 0.02951667],
       [0.30652365, 0.14051958, 0.67610251],
       [0.07630431, 0.55635423, 0.6505491 ],
       [0.69814769, 0.32170727, 0.92147648]])

In [0]:
b = torch.from_numpy(a)
b

tensor([[0.2256, 0.4552, 0.0295],
        [0.3065, 0.1405, 0.6761],
        [0.0763, 0.5564, 0.6505],
        [0.6981, 0.3217, 0.9215]], dtype=torch.float64)

In [0]:
b.numpy(), b

(array([[0.22563518, 0.45516341, 0.02951667],
        [0.30652365, 0.14051958, 0.67610251],
        [0.07630431, 0.55635423, 0.6505491 ],
        [0.69814769, 0.32170727, 0.92147648]]),
 tensor([[0.2256, 0.4552, 0.0295],
         [0.3065, 0.1405, 0.6761],
         [0.0763, 0.5564, 0.6505],
         [0.6981, 0.3217, 0.9215]], dtype=torch.float64))

The memory is shared betweenthe Numpy array and torch tensor, so if u change the value in-place of one object, the other will change as well.


In [0]:
#multiply b torch by 2, in place
b.mul_(2)

tensor([[0.4513, 0.9103, 0.0590],
        [0.6130, 0.2810, 1.3522],
        [0.1526, 1.1127, 1.3011],
        [1.3963, 0.6434, 1.8430]], dtype=torch.float64)

In [0]:
a

array([[0.45127036, 0.91032683, 0.05903334],
       [0.6130473 , 0.28103915, 1.35220502],
       [0.15260862, 1.11270847, 1.30109819],
       [1.39629539, 0.64341454, 1.84295296]])

Visit this link for more details - 

https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/Part%201%20-%20Tensors%20in%20PyTorch%20(Solution).ipynb